FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates tzdata curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY app.py scheduler.py /app/
COPY templates /app/templates
COPY static /app/static
COPY vclib.py /app/

# Crear directorio para logs
RUN mkdir -p /var/log/vmlabs

CMD ["python", "scheduler.py"]
